osx_image: xcode12

language: node_js
node_js: '14'

sudo: required

addons:
  chrome: stable 
  apt:
    packages:
      - xvfb

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  yarn: true
  directories:
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds

before_cache:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then rm -rf $HOME/.cache/electron-builder/wine; fi

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install yarn; fi
  - yarn

script:
  - echo "Unit Tests"
  - yarn test

os:
  - linux
  - osx